### ISSUE TITLE
tokenizer.pad_token = "!"

### ISSUE THREAD

**Issue by turian** [PrakharSaxena24/RepoForLLMs#2]
Why?

**Comment by PrakharSaxena24** [comment]
Thank you for raising this question.

In order to train models with batched input, it is important that all input sequences are of the same size, necessitating the use of a padding token. Unfortunately, the Mixtral tokenizer does not have a padding token set by default.

Now you can either add a new PAD token, or use an existing one as PAD token. I dont recommend adding a new PAD token, as that will require you to increase the vocabulary ( also the new token might not be learnt properly if the dataset is small).

So it is better to use another token as PAD token.
Commonly, you may find tutorials suggesting the use of:
`
tokenizer.pad_token = tokenizer.eos_token
`
However, using end-of-sequence (EOS) token as the padding token leads the model to ignore the EOS token during training, since padding tokens are not considered in loss calculations in the data collator we are using (https://github.com/huggingface/transformers/blob/09f9f566de83eef1f13ee83b5a1bbeebde5c80c1/src/transformers/data/data_collator.py#L750)
. This can prevent the model from learning where to stop generating text, which is particularly problematic for models intended for dialogues.

To address this, the padding token should be set to a token other than the EOS token. The "unknown" (UNK) token is often a good choice because it is neutral and does not influence the model's training in specific ways.
 In my case, I used the "!" token when adapting code from a previous project involving the Llama model, which does not recognize an UNK token. The "!" was selected because it rarely appeared in the dataset I was using.

For Mixtral/Mistral and similar tokenizers, I recommend using the UNK token. For Llama or other models without an UNK token, choose a token that is infrequently or never seen in your training dataset.

BTW, for a challenge,you could also just write your own data collator to solve the problem.
